export type Locale = "sr" | "en";

export const LANG_STORAGE_KEY = "bj-lang";

export const NAV_LINKS = [
  { href: "/", key: "home" },
  { href: "/gallery", key: "gallery" },
  { href: "/menu", key: "menu" },
  { href: "/contact", key: "contact" },
] as const;

export const OVERLAY_LINKS = NAV_LINKS.filter((item) => item.key !== "contact");

export type NavKey = (typeof NAV_LINKS)[number]["key"];

export const CHROME = {
  sr: {
    home: "Početna",
    gallery: "Galerija",
    menu: "Meni",
    contact: "Kontakt",
    languageLabel: "Jezik",
    openMenu: "Otvori meni",
    closeMenu: "Zatvori meni",
    galleryLine: "Neki trenuci jednostavno bolje izgledaju uživo.",
    viewFullGallery: "Pogledaj celu galeriju",
    menuTeaserHeading: "Naš meni",
    viewFullMenu: "Ceo meni",
    testimonialsKicker: "Utisci",
    testimonialsHeading: "Reči naših gostiju",
    viewAllReviews: "Sve recenzije",
    lightboxClose: "Zatvori",
    lightboxNext: "Sledeća",
    lightboxPrev: "Prethodna",
    contactKicker: "Kontakt i rezervacije",
    contactHeading: "Poseti nas",
    addressLabel: "Adresa",
    hoursLabel: "Radno vreme",
    hoursValue: "Svaki dan 07:30–23:30",
    phoneLabel: "Telefon",
    emailLabel: "Email",
    instagramLabel: "Instagram",
    mapCta: "Otvori u Google Maps",
    tabInquiry: "Upit",
    tabReservation: "Rezervacija proslave",
    reservationDisclaimer:
      "Poruka stiže na WhatsApp kafića. Odgovaramo u najkraćem roku.",
    pickerTimeRule: "Termini od sutra, svakog punog sata 08–21 h.",
    fieldName: "Ime i prezime",
    fieldPhone: "Telefon",
    fieldMessage: "Poruka",
    fieldDate: "Datum",
    fieldTime: "Vreme",
    fieldDateTime: "Datum i vreme",
    placeholderDateTime: "Izaberite datum i vreme *",
    pickerClose: "Zatvori",
    noTimeSlots: "Nema slobodnih termina za ovaj dan.",
    fieldGuests: "Broj gostiju",
    fieldCelebration: "Detalji proslave",
    placeholderName: "Vaše ime *",
    placeholderPhone: "Broj telefona *",
    placeholderMessage: "Kako vam možemo pomoći? *",
    placeholderCelebration: "Rođendan, godišnjica ili drugi povod *",
    placeholderGuests: "npr. 12 *",
    submit: "Pošalji",
    submitting: "Slanje…",
    submitSuccess:
      "Zahtev je uspešno poslat. Kontaktiraćemo vas uskoro.",
    submitError: "Došlo je do greške. Pokušajte ponovo.",
    validationRequired: "Ovo polje je obavezno.",
    validationPhone: "Unesite ispravan broj telefona.",
    validationMessageLength: "Poruka može imati najviše 500 karaktera.",
    validationGuests: "Unesite broj gostiju od 1 do 50.",
    validationDate: "Izaberite dostupan datum.",
    validationTime: "Izaberite dostupan termin.",
    selectDate: "Izaberite datum",
    selectTime: "Izaberite vreme",
    charCounter: (current: number, max: number) => `${current}/${max}`,
    footerCopyright: "© 2026 Bistro & Jars Coffee Bar",
    notFoundCode: "404",
    notFoundHeading: "Ova stranica ne postoji.",
    notFoundBody:
      "Adresa koju ste otvorili nije deo našeg sajta. Vratite se na početnu stranicu.",
    notFoundHomeCta: "Početna",
  },
  en: {
    home: "Home",
    gallery: "Gallery",
    menu: "Menu",
    contact: "Contact",
    languageLabel: "Language",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    galleryLine: "Some moments simply look better in person.",
    viewFullGallery: "View full gallery",
    menuTeaserHeading: "Our menu",
    viewFullMenu: "View full menu",
    testimonialsKicker: "Reviews",
    testimonialsHeading: "Words from our guests",
    viewAllReviews: "All reviews",
    lightboxClose: "Close",
    lightboxNext: "Next",
    lightboxPrev: "Previous",
    contactKicker: "Contact & reservations",
    contactHeading: "Visit us",
    addressLabel: "Address",
    hoursLabel: "Opening hours",
    hoursValue: "Open daily 07:30–23:30",
    phoneLabel: "Phone",
    emailLabel: "Email",
    instagramLabel: "Instagram",
    mapCta: "Open in Google Maps",
    tabInquiry: "Inquiry",
    tabReservation: "Celebration booking",
    reservationDisclaimer:
      "Your message goes to the café's WhatsApp. We reply as soon as possible.",
    pickerTimeRule: "Slots from tomorrow, on the hour 08:00–21:00.",
    fieldName: "Full name",
    fieldPhone: "Phone",
    fieldMessage: "Message",
    fieldDate: "Date",
    fieldTime: "Time",
    fieldDateTime: "Date & time",
    placeholderDateTime: "Choose date and time *",
    pickerClose: "Close",
    noTimeSlots: "No available slots on this day.",
    fieldGuests: "Number of guests",
    fieldCelebration: "Celebration details",
    placeholderName: "Your name *",
    placeholderPhone: "Phone number *",
    placeholderMessage: "How can we help? *",
    placeholderCelebration: "Birthday, anniversary, or another occasion *",
    placeholderGuests: "e.g. 12 *",
    submit: "Send",
    submitting: "Sending…",
    submitSuccess:
      "Your request has been sent successfully. We will contact you shortly.",
    submitError: "Something went wrong. Please try again.",
    validationRequired: "This field is required.",
    validationPhone: "Enter a valid phone number.",
    validationMessageLength: "Message can be at most 500 characters.",
    validationGuests: "Enter a guest count between 1 and 50.",
    validationDate: "Choose an available date.",
    validationTime: "Choose an available time slot.",
    selectDate: "Select date",
    selectTime: "Select time",
    charCounter: (current: number, max: number) => `${current}/${max}`,
    footerCopyright: "© 2026 Bistro & Jars Coffee Bar",
    notFoundCode: "404",
    notFoundHeading: "This page doesn't exist.",
    notFoundBody:
      "The address you opened isn't part of our site. Head back to the home page.",
    notFoundHomeCta: "Home",
  },
} as const;
